export const FETCH_SEASONS_BY_ID_SUCCESS = 'FETCH_SEASONS_BY_ID_SUCCESS';
export const FETCH_SEASONS_BY_ID_ERROR = 'FETCH_SEASONS_BY_ID_ERROR';
export const FETCH_SEASONS_BY_CLUBID_SUCCESS = 'FETCH_SEASONS_BY_CLUBID_SUCCESS';
export const FETCH_SEASONS_BY_CLUBID_ERROR = 'FETCH_SEASONS_BY_CLUBID_ERROR';