export const FETCH_TRAININGS_BY_ID_SUCCESS = 'ETCH_TRAININGS_BY_ID_SUCCESS';
export const ETCH_TRAININGS_ID_ERROR = 'ETCH_TRAININGS_BY_ID_ERROR';
export const FETCH_TRAININGS_BY_COACH_ID_SUCCESS = 'FETCH_TRAININGS_BY_COACH_ID_SUCCESS';
export const FETCH_TRAININGS_BY_COACH_ID_ERROR = 'FETCH_TRAININGS_BY_COACH_ID_ERROR';

