export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';
export const FETCH_MATCHES_BY_ID_SUCCESS  = 'FETCH_MATCHES_BY_ID_SUCCESS';
export const FETCH_MATCHES_REQUEST  = 'FETCH_MATCHES_REQUEST';
export const FETCH_MATCHES_BY_ID_ERROR = 'FETCH_MATCHES_BY_ID_ERROR';
export const FETCH_NEXT_MATCHES_SUCCESS  = 'FETCH_NEXT_MATCHES_SUCCESS';
export const FETCH_NEXT_MATCHES_ERROR = 'FETCH_NEXT_MATCHES_ERROR';
export const FETCH_NEXT_MATCHES_REQUEST = 'FETCH_NEXT_MATCHES_REQUEST';

