export const FETCH_ROLES_BY_NAME_SUCCESS = 'FETCH_ROLES_BY_NAME_SUCCESS';
export const FETCH_ROLES_BY_NAME_ERROR = 'FETCH_ROLES_BY_NAME_ERROR';
export const FETCH_ROLES_BY_NAME_REQUEST= 'FETCH_ROLES_BY_NAME_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_ERROR = 'FETCH_ROLES_ERROR';
export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';